<?php

namespace App\Services\Docker;

use App\Models\Task;
use App\Services\FirewallManager;
use App\Services\Shell;
use Illuminate\Support\Str;
use Illuminate\Validation\ValidationException;

/** One-Click Install: compose apps from config/docker_apps.php. */
class AppStore
{
    public function __construct(protected ComposeManager $compose) {}

    public function categories(): array
    {
        return config('docker_apps.categories', []);
    }

    public function apps(): array
    {
        return config('docker_apps.apps', []);
    }

    public function app(string $slug): ?array
    {
        return $this->apps()[$slug] ?? null;
    }

    /** Installed apps: [slug => [project names]]. */
    public function installed(): array
    {
        $out = [];
        foreach ($this->compose->projects() as $project) {
            if ($project['app']) {
                $out[$project['app']][] = $project['name'];
            }
        }

        return $out;
    }

    /** TCP ports already listening on the host. */
    public function usedPorts(): array
    {
        if (Shell::simulating()) {
            return [22, 80, 443, 3000, 3306, 6333, 6334, 8080, 8888, 9998];
        }
        $out = Shell::out("ss -ltnH 2>/dev/null | awk '{print \$4}' | sed 's/.*://' | sort -un", 10);

        return array_map('intval', array_filter(explode("\n", $out), 'is_numeric'));
    }

    /** Value written to .env: plain when safe, single-quoted otherwise. */
    public static function envValue(string $value): string
    {
        if (str_contains($value, "\n") || str_contains($value, "\r") || str_contains($value, "'")) {
            throw new \InvalidArgumentException('Values cannot contain quotes or line breaks.');
        }

        return preg_match('/^[A-Za-z0-9_.:\/@%+,=-]*$/', $value) ? $value : "'{$value}'";
    }

    /**
     * Validate the install form and build the .env of an app.
     *
     * @return array{env: string, values: array<string, string>, ports: list<int>}
     */
    public function prepare(array $app, array $input, bool $external): array
    {
        $values = [];
        $ports = [];
        $errors = [];
        $used = null;

        foreach ($app['fields'] ?? [] as $key => $field) {
            $value = trim((string) ($input[$key] ?? ''));
            $label = $field['label'] ?? $key;
            switch ($field['type'] ?? 'text') {
                case 'port':
                    $value = $value === '' ? (string) ($field['default'] ?? '') : $value;
                    if (! ctype_digit($value) || (int) $value < 1 || (int) $value > 65535) {
                        $errors[$key] = "{$label} must be between 1 and 65535.";
                        break;
                    }
                    $used ??= $this->usedPorts();
                    if (in_array((int) $value, $used, true) || in_array((int) $value, $ports, true)) {
                        $errors[$key] = "{$label} {$value} is already in use.";
                    }
                    $ports[] = (int) $value;
                    break;
                case 'password':
                    $value = $value === '' ? Str::random(24) : $value;
                    if (strlen($value) < 8) {
                        $errors[$key] = "{$label} must have at least 8 characters.";
                    }
                    break;
                case 'email':
                    $value = $value === '' ? (string) ($field['default'] ?? '') : $value;
                    if (! filter_var($value, FILTER_VALIDATE_EMAIL)) {
                        $errors[$key] = "{$label} must be a valid email.";
                    }
                    break;
                case 'select':
                    $value = $value === '' ? (string) ($field['default'] ?? '') : $value;
                    if (! array_key_exists($value, $field['options'] ?? [])) {
                        $errors[$key] = "Choose a valid {$label}.";
                    }
                    break;
                default:
                    $value = $value === '' ? (string) ($field['default'] ?? '') : $value;
                    if ($value === '' || strlen($value) > 255) {
                        $errors[$key] = "{$label} is required (max 255 characters).";
                    }
            }
            if (! isset($errors[$key])) {
                try {
                    self::envValue($value);
                } catch (\InvalidArgumentException $e) {
                    $errors[$key] = $label.': '.$e->getMessage();
                }
            }
            $values[$key] = $value;
        }
        if ($errors) {
            throw ValidationException::withMessages($errors);
        }

        $env = "# Generated by GBX Panel for {$app['name']}\nBIND_IP=".($external ? '0.0.0.0' : '127.0.0.1')."\n";
        foreach ($values as $key => $value) {
            $env .= $key.'='.self::envValue($value)."\n";
        }

        return ['env' => $env, 'values' => $values, 'ports' => $ports];
    }

    /** @return array{task: Task, project: string, ports: list<int>} */
    public function install(string $slug, string $project, array $input, bool $external): array
    {
        $app = $this->app($slug) ?? throw new \InvalidArgumentException('Unknown app');
        $prepared = $this->prepare($app, $input, $external);

        $created = $this->compose->create($project, $app['compose'], $prepared['env'], $slug);
        if ($created->failed()) {
            throw ValidationException::withMessages(['project' => $created->message()]);
        }

        if ($external && $prepared['ports']) {
            $firewall = app(FirewallManager::class);
            if ($firewall->installed()) {
                foreach ($prepared['ports'] as $port) {
                    $firewall->addRule('allow', (string) $port, 'tcp', null, "Docker {$project}");
                }
            }
        }

        $dir = ComposeManager::root().'/'.$project;
        $projectData = [
            'name' => $project, 'dir' => $dir, 'files' => [$dir.'/compose.yaml'],
            'running' => 0, 'total' => 0, 'status' => 'stopped', 'created' => time(), 'app' => $slug, 'managed' => true,
        ];
        $first = $prepared['ports'][0] ?? null;
        $after = $first ? 'echo "Open: http://'.($external ? "\$(hostname -I | awk '{print \$1}')" : '127.0.0.1').':'.$first.'"' : null;

        return [
            'task' => $this->compose->upTask($projectData, true, "Install {$app['name']} ({$project})", ['after' => $after]),
            'project' => $project,
            'ports' => $prepared['ports'],
        ];
    }
}
